### ISSUE TITLE
flit_ptu initiallization error

### ISSUE THREAD

**Issue by RoboEvangelist** [ros-drivers/flir_ptu#14]
Hi Folks,

When I run the roslaunch for the ptu.launch, I get the next sequence of errors:

[ERROR] [1423699913.432927534]: Error getting pan-tilt res
[ERROR] [1423699913.632242150]: Error getting pan-tilt res
[ERROR] [1423699913.831551307]: Error getting pan-tilt limit
[ERROR] [1423699914.030850575]: Error getting pan-tilt limit
[ERROR] [1423699914.230154086]: Error getting pan-tilt limit
[ERROR] [1423699914.429461662]: Error getting pan-tilt limit
[ERROR] [1423699914.628747865]: Error getting pan-tilt limit
[ERROR] [1423699914.828042120]: Error getting pan-tilt limit
[ERROR] [1423699915.027332077]: Error getting pan-tilt limit
[ERROR] [1423699915.226578932]: Error getting pan-tilt limit
[ERROR] [1423699915.226634618]: Could not initialize FLIR PTU on /dev/ttyS1

Why does that happen?
Thanks

**Comment by mikepurvis** [comment]
Alas, we don't have this hardware in-house at the moment, so I'm not able to reproduce the problem you're seeing. However, can you indicate which model of PTU you have (D46?), and confirm that it's connected to ttyS1 on your machine?

**Comment by RoboEvangelist** [comment]
My model is PTU-46-70

**Comment by srsidd** [comment]
Hi @RoboEvangelist 
I'm using an E46 and I'm getting the same error. I know it's been a while but do you remember how you fixed this?
